export const newslist = [
  {
    title: `PlayStation Plus Free Games For September 2022 Revealed`,
    imageURL: require('../img/4029176-ps-plus-sep-logo-promo1-2-thumb-1.jpg'),
    fullNews: ["Following a leak, PlayStation has confirmed the next batch of PlayStation Plus freebies.",
    "September 2022's PS Plus Essential lineup will include Need for Speed Heat, Toem, and Granblue Fantasy: Versus. All three of those games are worth playing, so it'll be a pretty good month overall for freebies on PlayStation.",
    "The new batch of games will be available to claim starting September 6. As a reminder, all PS Plus subscribers, regardless of tier, can claim the PlayStation Plus Essential lineup each month. More games are also available for Extra and Premium members.",
    "Need for Speed Heat is the best-known game of the bunch. It's the latest entry (not including remasters) in the long-running EA racing franchise and a turn in the right direction. The franchise went down a bumpy road throughout the 2010s, but Need for Speed Heat recaptured the pure arcade racing fun that the series was known for in its early days.",
    "Featuring a cool night-and-day system in which you compete in sanctioned events by day and illegal street races after dark, Need for Speed Heat offers a decent amount of variety that keeps the arcade racing fresh throughout its roughly 10-hour runtime. It earned a 7/10 in our Need for Speed Heat review. Need for Speed Heat doesn't have a PS5 upgrade, but you can play it on the latest PlayStation console via backwards compatibility.",
    "Toem is a charming indie that released just last year. You play as a young photographer in search of a snapshot of the eponymous Toem phenomenon. If you're looking for a relaxing game that won't take up too much time, Toem is a good choice. The gameplay revolves around solving puzzles by taking photographs of the world around you. The black-and-white visuals are lovely, and the gameplay is complemented by a beautiful soundtrack. Only the PS5 version of Toem will be available to claim in September.",
    "Fighting game fans can check out Granblue Fantasy: Versus, a 2.5D fighting game developed by Arc System Works. Featuring the characters that first appeared in the Granblue Fantasy mobile game in 2014, Versus is a stylish fighter with great mechanics. It also implements RPG systems, which is fitting considering the first Granblue Fantasy game was an RPG. The single-player campaign isn't very exciting, but the core fighting mechanics are great. It earned a 7/10 in our Granblue Fantasy: Versus review.If you haven't already, make sure to claim August's freebies before they leave PlayStation Plus on September 6.", 
    "August's lineup includes Yakuza: Like a Dragon, Tony Hawk's Pro Skater 1 + 2, and Little Nightmares.PlayStation is also adding new games to the PS Plus Extra/Premium library next month, including Deathloop, Chicory: A Colorful Tale, and Assassin's Creed Origins."],
    isBigNews: true,
    id: '1',
    dateOfWriting: 'Saturday, September 3, 2022 at 3:37 PM',
    tag: 'console',
    editedBy: 'Vasya Pupkin'
  },
  {
    title: 'Xbox Games With Gold Free Games For September 2022 Revealed',
    imageURL: require('../img/4028692-xbox-games-gold-sept-promo1-2-thumb-1.jpg'),
    fullNews: ["We're at the start of another new month, so that means that it's time to claim some freebies on Xbox Store--if you're a Game Pass Ultimate or Xbox Live Gold subscriber, of course. September's Games with Gold lineup currently features Gods Will Fall and Thrillville.", 
    "You can also still claim one of August's freebies, ScourgeBringer, until September 16. Halfway through the month the lineup will refresh with Double Kick Heroes and Portal 2.",  
    "As a reminder, it's the last month for original Xbox and Xbox 360 freebies in the Games with Gold program. But keep in mind that you will be able to keep all of the backwards compatible games you've claimed up until now, even if your Xbox Live Gold subscription lapses.", 
    "That means Portal 2 will be free to keep, which is pretty cool.    Portal 2 is the star of the show in September. The classic puzzle-shooter is widely considered to be one of the best games of its era. The sequel expanded greatly on the already-brilliant foundation of the original. Featuring a campaign that's roughly double the length of its predecessor, Portal 2 added some seriously great mechanics to the formula. If you've never played Portal 2, do yourself a favor and check it out next month. It even has a separate cooperative campaign that you can play alongside a friend.", 
    "Portal 2 will be free in the back half of September.",
    "Prior to Portal 2 landing on the service, you can add Thrillville to your Xbox library. Thrillville is an amusement park management sim that originally released in 2006. If you've ver played Rollercoaster Tycoon, Thrillville isn't all that different, but it does have an actual narrative. Along with managing the park's day-to-day activities, you have to complete missions to move on. There are five parks in total to oversee. Thrillville also has a bunch of mini-games that can be played solo or with friends. You can grab Thrillville until September 15.We started with the backwards-compatible classics because they are just a bit more exciting than the Xbox One games for September.", 
    "All month long subscribers will be able to claim Gods Will Fall, an action game that released last year. You play as a Celtic warrior in a fight against a numerous gods that control the world. Gods Will Fall does offer an interesting spin on the roguelike genre and features challenging combat, so it's worth checking out if you like those sorts of action games."],
    isBigNews: true,
    id: '2',
    dateOfWriting: 'Friday, September 2, 2022 at 16:37 PM',
    tag: 'console',
    editedBy: 'George Orwell'
  },
  {
    title: 'The Next-Gen Witcher 3 Release Is Still On Track For This Year',
    imageURL: require('../img/4032650-3060670-the_witcher_3_wild_hunt_blood_and_wine_toussaint_is_full_of_places_just_waiting_to_be_discovered_rgb.jpg'),
    fullNews: ["The next-gen release of The Witcher 3: Wild Hunt is still on track for release this year, CD Projekt has confirmed in its latest earnings call, with the slide showing a Q4 2022 release window.",
    "The PS5 and Xbox Series X|S editions have been delayed a number of times, originally intended for release in 2021, and then for earlier in 2022.",
    "The Q4 release window means the game should be out between October and Decemberthis year, with CD Projekt likely to be aiming for a release in time for the holidays.",
    "The release will be a 'Complete Edition' of Witcher 3 including all its expansions, with all content enhanced for next-gen consoles. The PS5 and Xbox Series X|S versions of the game will also come with all-new free DLCs inspired by the Witcher Netflix series"],
    isBigNews: true,
    id: '3',
    dateOfWriting: 'Thursday, September 1, 2022 at 11:37 AM',
    tag: 'PC',
    editedBy: 'Alex Sytnik'
  },
  {
    title: `PlayStation Plus Free Games For September 2022 Revealed2`,
    imageURL: require('../img/4029176-ps-plus-sep-logo-promo1-2-thumb-1.jpg'),
    fullNews: ["Following a leak, PlayStation has confirmed the next batch of PlayStation Plus freebies.",
    "September 2022's PS Plus Essential lineup will include Need for Speed Heat, Toem, and Granblue Fantasy: Versus. All three of those games are worth playing, so it'll be a pretty good month overall for freebies on PlayStation.",
    "The new batch of games will be available to claim starting September 6. As a reminder, all PS Plus subscribers, regardless of tier, can claim the PlayStation Plus Essential lineup each month. More games are also available for Extra and Premium members.",
    "Need for Speed Heat is the best-known game of the bunch. It's the latest entry (not including remasters) in the long-running EA racing franchise and a turn in the right direction. The franchise went down a bumpy road throughout the 2010s, but Need for Speed Heat recaptured the pure arcade racing fun that the series was known for in its early days.",
    "Featuring a cool night-and-day system in which you compete in sanctioned events by day and illegal street races after dark, Need for Speed Heat offers a decent amount of variety that keeps the arcade racing fresh throughout its roughly 10-hour runtime. It earned a 7/10 in our Need for Speed Heat review. Need for Speed Heat doesn't have a PS5 upgrade, but you can play it on the latest PlayStation console via backwards compatibility.",
    "Toem is a charming indie that released just last year. You play as a young photographer in search of a snapshot of the eponymous Toem phenomenon. If you're looking for a relaxing game that won't take up too much time, Toem is a good choice. The gameplay revolves around solving puzzles by taking photographs of the world around you. The black-and-white visuals are lovely, and the gameplay is complemented by a beautiful soundtrack. Only the PS5 version of Toem will be available to claim in September.",
    "Fighting game fans can check out Granblue Fantasy: Versus, a 2.5D fighting game developed by Arc System Works. Featuring the characters that first appeared in the Granblue Fantasy mobile game in 2014, Versus is a stylish fighter with great mechanics. It also implements RPG systems, which is fitting considering the first Granblue Fantasy game was an RPG. The single-player campaign isn't very exciting, but the core fighting mechanics are great. It earned a 7/10 in our Granblue Fantasy: Versus review.If you haven't already, make sure to claim August's freebies before they leave PlayStation Plus on September 6.", 
    "August's lineup includes Yakuza: Like a Dragon, Tony Hawk's Pro Skater 1 + 2, and Little Nightmares.PlayStation is also adding new games to the PS Plus Extra/Premium library next month, including Deathloop, Chicory: A Colorful Tale, and Assassin's Creed Origins."],
    isBigNews: false,
    id: '4',
    dateOfWriting: 'Thursday, September 1, 2022 at 11:37 AM',
    tag: 'console',
    editedBy: 'Vasya Pupkin'
  },
  {
    title: 'Xbox Games With Gold Free Games For September 2022 Revealed2',
    imageURL: require('../img/4028692-xbox-games-gold-sept-promo1-2-thumb-1.jpg'),
    fullNews: ["We're at the start of another new month, so that means that it's time to claim some freebies on Xbox Store--if you're a Game Pass Ultimate or Xbox Live Gold subscriber, of course. September's Games with Gold lineup currently features Gods Will Fall and Thrillville.", 
    "You can also still claim one of August's freebies, ScourgeBringer, until September 16. Halfway through the month the lineup will refresh with Double Kick Heroes and Portal 2.",  
    "As a reminder, it's the last month for original Xbox and Xbox 360 freebies in the Games with Gold program. But keep in mind that you will be able to keep all of the backwards compatible games you've claimed up until now, even if your Xbox Live Gold subscription lapses.", 
    "That means Portal 2 will be free to keep, which is pretty cool.    Portal 2 is the star of the show in September. The classic puzzle-shooter is widely considered to be one of the best games of its era. The sequel expanded greatly on the already-brilliant foundation of the original. Featuring a campaign that's roughly double the length of its predecessor, Portal 2 added some seriously great mechanics to the formula. If you've never played Portal 2, do yourself a favor and check it out next month. It even has a separate cooperative campaign that you can play alongside a friend.", 
    "Portal 2 will be free in the back half of September.",
    "Prior to Portal 2 landing on the service, you can add Thrillville to your Xbox library. Thrillville is an amusement park management sim that originally released in 2006. If you've ver played Rollercoaster Tycoon, Thrillville isn't all that different, but it does have an actual narrative. Along with managing the park's day-to-day activities, you have to complete missions to move on. There are five parks in total to oversee. Thrillville also has a bunch of mini-games that can be played solo or with friends. You can grab Thrillville until September 15.We started with the backwards-compatible classics because they are just a bit more exciting than the Xbox One games for September.", 
    "All month long subscribers will be able to claim Gods Will Fall, an action game that released last year. You play as a Celtic warrior in a fight against a numerous gods that control the world. Gods Will Fall does offer an interesting spin on the roguelike genre and features challenging combat, so it's worth checking out if you like those sorts of action games."],
    isBigNews: false,
    id: '5',
    dateOfWriting: 'Thursday, September 1, 2022 at 11:35 AM',
    tag: 'console',
    editedBy: 'George Orwell'
  },
  {
    title: 'The Next-Gen Witcher 3 Release Is Still On Track For This Year',
    imageURL: require('../img/4032650-3060670-the_witcher_3_wild_hunt_blood_and_wine_toussaint_is_full_of_places_just_waiting_to_be_discovered_rgb.jpg'),
    fullNews: ["The next-gen release of The Witcher 3: Wild Hunt is still on track for release this year, CD Projekt has confirmed in its latest earnings call, with the slide showing a Q4 2022 release window.",
      "The PS5 and Xbox Series X|S editions have been delayed a number of times, originally intended for release in 2021, and then for earlier in 2022.",
      "The Q4 release window means the game should be out between October and December  this year, with CD Projekt likely to be aiming for a release in time for the holidays.",
      " The release will be a 'Complete Edition' of Witcher 3 including all its expansions, with all content enhanced for next-gen consoles. The PS5 and Xbox Series X|S versions of the game will also come with all-new free DLCs inspired by the Witcher Netflix series"],
      isBigNews: false,
    id: '6',
    dateOfWriting: 'Thursday, September 1, 2022 at 11:37 AM',
    tag: 'PC',
    editedBy: 'George Orwell'
  },
  {
    title: 'The Next-Gen Witcher 3 Release Is Still On Track For This Year',
    imageURL: require('../img/4032650-3060670-the_witcher_3_wild_hunt_blood_and_wine_toussaint_is_full_of_places_just_waiting_to_be_discovered_rgb.jpg'),
    fullNews: ["The Division Resurgence is a new mobile game based in the universe of The Division coming soon to iOS and Android devices. Like its console and PC counterparts, it will be a co-op third-person-shooter RPG with a separate story that will be canonical to the larger universe. ",
      "Alongside the new story, the mobile game also features different classes, new gear and weapons, and new characters. Resurgence takes place in New York City and according to the press release will offer 'a unique perspective on key story events that have taken place in The Division and The Division 2' with players taking on the role of first-wave agents. The original Division takes place in Manhattan while the sequel takes place in Washington DC.",
      " is still on track for release this year, CD Projekt has confirmed in its latest earnings call, with the slide showing a Q4 2022 release window. The PS5 and Xbox Series X|S editions have been delayed a number of times, originally intended for release in 2021, and then for earlier in 2022.",
      "Ubisoft is referring to the game as open-world and says players will be able to roam freely around the urban environment and will feature both story missions and world activities for cooperative agents to complete. Ubisoft says the game can also be played alone.",
      "Ubisoft does not yet have a release date for The Division Resurgence, but you can opt to participate in upcoming tests (the press release for the game poitedly does not call it a beta) for the game by visiting the official website.",
      " GameSpot gave the original game an 8/10 in its The Division review. In its The Division 2 review, GameSpot gave the sequel a 9/10."],
    isBigNews: false,
    id: '7',
    dateOfWriting: 'Thursday, September 1, 2022 at 11:39 AM',
    tag: 'PC',
    editedBy: 'Alex Sytnik'
  },
  {
    title: 'Get Up To 7 PC Games For Just $10 In This New Fanatical Bundle',
    imageURL: require('../img/4036291-gsstratbundle3.png'),
    fullNews: ["For a limited time, you can snag up to seven PC strategy games for just $10 through Fanatical’s new Build Your Own Strategy Bundle 3. ",
      "If you’re unfamiliar with Fanatical’s Build Your Own bundles, these deals let you select from a pool of discounted games, and the total price scales based on how many you add to your cart. The Build Your Own Strategy 3 bundle includes 16 games, and you can select three for $5, five for $8, or seven for $10.",
      " The list of possible games includes titles from every corner of the strategy genre, including turn-based fantasy wargaming like Fantasy General II: Invasion , RTS games like Iron Marines , and management sims like Train Valley 2 .",
      "There are also some interesting hybrid strategy titles, such as Monster Sanctuary , a 2D Metroidvania platformer with monster taming and turn-based RPG battles, the side-scrolling tactical combat game Recon Control , and top-down tactical “dash ‘n slasher” Red Ronin .",
      "We have the complete list of games in Fanatical’s Build Your Own Strategy Bundle 3 below. If something catches your eye, head over and purchase the bundle quickly--it’s only available until September 27.",
      ],
    isBigNews: true,
    id: '8',
    dateOfWriting: 'Thursday, September 1, 2022 at 11:37 AM',
    tag: 'PC',
    editedBy: 'Alex Sytnik'
  },
  {
    title: 'GeCall Of Duty: Warzone Mobile Is A Separate Game, Not A Port',
    imageURL: require('../img/4036023-cropwarzone-mobile---jump-keyart.jpg'),
    fullNews: ["Call of Duty: Warzone Mobile (formerly known as Project Aurora) received its proper, finalized title during GameSpot's recent Swipe mobile showcase, but today, during Activision's Call of Duty Next event, the game was fully unveiled. Activision is hoping to offer a genuine Warzone experience with 120 online players, a huge map, vehicles, and mechanics like the Gulag, all on iOS and Android devices.",
      "You can see the game's trailer below, but we also had a chance to speak with Activision's VP of mobile, Chris Plummer, about its plans for Warzone Mobile and clarify exactly how cross-progression will work between Warzone and Warzone Mobile, what will happen to the battle royale mode currently available in Call of Duty Mobile, and whether this is considered a port, or a separate game.",
      " Are you ready to share when Call of Duty: Warzone Mobile is releasing?.",
      "Chris Plummer: We'll be out next year. We haven't released a fixed release date, so more on that over time. But right now we're revealing the gameplay for the first time. People have hands on it and are checking it out during the live stream event. And then over time we'll see more of the experience and next year we'll be out there for everybody.",
      "Is Warzone Mobile considered a port of Call of Duty: Warzone?",
      "No, it is not a port. We have shared technology. We have a lot of advantages, but we're making a mobile-first experience. Our priority is to make the best possible experience for mobile players, regardless of which platform you typically play on. There are plenty of players that mobile is their first and primary platform. There are other folks who are going to come over because they play Warzone on another platform and might want to get an extra match in and we want to make sure that the game works for everybody."
    ],
    isBigNews: true,
    id: '9',
    dateOfWriting: 'Thursday, September 1, 2022 at 08:37 AM',
    tag: 'mobile',
    editedBy: 'Alex Sytnik'
  },
  {
    title: 'Project Aurora Is Now Call Of Duty Warzone Mobile',
    imageURL: require('../img/4032343-screenshot2022-09-07at3.02.36pm.png'),
    fullNews: ["Call of Duty: WarzoDuring GameSpot's new mobile show, Swipe, Activision shared the first teaser trailer and finalized name for Call of Duty's new Warzone mobile game and revealed what's next for Call of Duty Mobile.",
      "Call of Duty Warzone Mobile is the official name of the game formerly known as Project Aurora. It's a new game from four Activision studios working together on the project, Solid State Studios, Beenox, Activision Shanghai, and Digital Legends, and today Activision is announcing the official title and revealing the first brief teaser.",
      "Call of Duty Warzone Mobile will be, as its name suggests, a mobile version of Call of Duty Warzone. The existing Call of Duty Mobile already has a battle royale element, in addition to standard multiplayer, but Call of Duty Warzone Mobile is exclusively a battle royale game.",
      "As for Call of Duty: Mobile, the game's new Season 8: Train to Nowhere update arrived on September 7 with a new map, Express, another battle pass, and much more. For more, check out this roundup of everything new in Season 8: Train to Nowhere.",
      "In addition to Call of Duty Warzone Mobile, Activision is developing Warzone 2.0 for console. Activision will share more details on the title during the big Call of Duty Next event on September 15."      
    ],
    isBigNews: true,
    id: '10',
    dateOfWriting: 'Thursday, August 1, 2022 at 01:37 AM',
    tag: 'mobile',
    editedBy: 'Alex Sytnik'
  },
  {
    title: 'Like A Dragon: Ishin Was Considered To Be An Impossible Port For Years By RGG',
    imageURL: require('../img/4035950-ishin.jpg'),
    fullNews: ["For many years, Like a Dragon: Ishin has been the one Yakuza game that western fans have been unable to get their hands on unless they were willing to import a copy or learn another language so that they could navigate the PlayStation storefront of Japan. A Japan-exclusive released on PS3 and PS4 in 2013, Like a Dragon: Ishin finally makes its way to the West next year and is being rebuilt entirely in Unreal Engine 4.",
      "Set in 1860s Kyo--a fictionalized version of Kyoto--Ishin's focus on the fall of the Samurai during a turbulent part of Japan's history was originally considered to be 'impossible' to localize by Ryu Ga Gotoku Studio head Masayoshi Yokoyama. According to Yokoyama, this was largely due to anachronistic challenges..",
      "When we were first working on Ishin, we thought this game was impossible to localize, Yokoyama explained. 'There was no way that the overseas team and the Asian team would be able to localize it. I don't think half the people would really understand what's going on. It's hard for Japanese people to understand, it's probably even harder for people overseas.'",
      "According to Yokoyama, concepts, philosophies, and unique language quirks of that historical time period proved to be extremely challenging for the localization teams, but the staff rose to the occasion for the Ishin remake. Several historical words and terms used in Ishin have lost their context in the modern Japanese language, but the game will have a special system in place that will explain their meaning to western audiences.",
      "RGG Studio bills the next mainline adventure as 'the largest [Yakuza] game to date' and will release it on PC, PS5, PS4, Xbox Series X, and Xbox One. Just don't expect a Switch port of any Yakuza game anytime soon, due to the series being 'too underground' for that family-friendly system according to Yokohama."      
    ],
    isBigNews: false,
    id: '11',
    dateOfWriting: 'Thursday, August 1, 2022 at 01:37 AM',
    tag: 'PC',
    editedBy: 'Alex Sytnik'
  },
]